function [X_data,Y_data] = AddMagneticField(N_p,d_int,graphType,x_pnt,y_pnt,interval,N,v)
%% Description
% Determine the magnetic field at 'x_pnt (for y-plot)' and 'y_pnt (for
% x-plot)' generated by multiple moving particles aligned in x-axis.
% We will use 'MagneticField.m' to calculate the magnetic field generate
% from a single moving particles and sum up all the magnetic field generated
% from multiple moving particles.  
%% Parameter setting
% examplar code: AddMagneticField(10,1e-4,'x',0,0.5e-4,1e-6,1,1)
 
% N_p = 10; % Number of particle
% d_int = 1e-4; % [meter] Interparticle spacing
% 
% N = 1; % Number of positive point charge consisting a group 
% v = 1; % [meter per second]
% interval = 1e-6; [meter]
% 
% graphType = 'x'; % Set this value as 'x' or 'y', if you want to plot the magnetic field with respect to 'x-axis' or 'y-axis', respectively.

% x_pnt = 0; y_pnt = 0.5e-4; % points where we monitor the magnetic field.

%% Particle location
x_lim = (N_p+2)*d_int/2;
y_lim = (N_p+2)*d_int/2;

if N_p/2 == 0
    x_loc = linspace(-1*N_p/2*d_int,N_p/2*d_int,N_p);
else
    x_loc = linspace(-1*(N_p-1)/2*d_int,(N_p-1)/2*d_int,N_p);
end
y_loc = 0;
%% Sum all the magnetic field generated by multiple of particles
for i = 1:N_p
    if i == 1
        [x,y,B] = MagneticField(x_loc(i),y_loc,x_lim,y_lim,interval,N,v);
    else
        [x,y,B_temp] = MagneticField(x_loc(i),y_loc,x_lim,y_lim,interval,N,v);
        B = B + B_temp;
    end
end

%clf('reset')
%figure(1)
%surf(x,y,B); xlabel('x distance (m)'); ylabel('y distance(m)');

figure(1)
switch graphType
    case 'x'
        [Val, Idx] = min(abs(y(:,1)-y_pnt));
        X_data = x(1,:); Y_data = B(Idx,:);
        plot(X_data,Y_data);
    case 'y'        
        [Val, Idx] = min(abs(x(1,:)-x_pnt));
        X_data = y(:,1); Y_data = B(:,Idx);
        plot(X_data,Y_data);
    otherwise
        warning('Unexpected plot type. No plot created.')
end
xlabel('distance (m)'); ylabel('Magnetic field (T)');
end